#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \

# Tom's Extra Stuff
alias \
	apl="ansible-playbook" \
        azcli="docker run -it -v ${HOME}/.ssh:/root/.ssh mcr.microsoft.com/azure-cli" \
        br="sudo lsof +c 0 | grep -w 'DEL.*lib' | awk '{print \$1}' | sort -u" \
        cat="bat" \
        cdg="cd $HOME/repos" \
        cdsi="cd $HOME/repos/si-ansible" \
        conky="conky --config=${XDG_CONFIG_HOME:-$HOME/.config}/conky/conky.conf" \
        cpa="scp si-satellite.si.edu:/etc/ansible/hosts . ; sudo cp hosts /etc/ansible/hosts ; rm hosts" \
        gpa='find ~ -name ".git" -type d -exec bash -c "echo '{}' && cd '{}'/.. && git pull" \;' \
        la="exa -arlg --time-style=long-iso --group-directories-first --icons -m -sold" \
        ls="exa -rlg --time-style=long-iso --group-directories-first --icons -m -sold" \
        ll="exa -rlg --time-style=long-iso --group-directories-first --icons -m -sold" \
        lt="exa -rltg --time-style=long-iso --group-directories-first --icons -m -sold" \
        rvim="sudo nvim" \
        sat="ssh si-satellite" \
        swork="ssh work" \
        tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
        vtop="vtop --theme=gruvbox" \
        yarn="yarn --use-yarnrc ${XDG_CONFIG_HOME:-$HOME/.config}/yarn/config"
